Repository Making-my-own-weapon/Coconut-Frontend, pull requests merged in 2025-07, with the labels that each got.

#41 feat(#40): JWT로그인 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/client.ts
  src/components/PrivateRoute.tsx
  src/components/common/Header.tsx
  src/components/common/HeaderLogout.tsx
  src/components/join/ActionCard.tsx
  src/components/join/GuestActionContainer.tsx
  src/components/join/GuestForm.tsx
  src/components/join/HostActionContainer.tsx
  src/components/join/HostForm.tsx
  src/components/login/LoginCard.tsx
  src/components/login/loginApi.ts
  src/components/main/FeatureCards.tsx
  src/components/main/HeroSection.tsx
  src/components/main/MainBackground.tsx
  src/components/signup/SignupCard.tsx
  src/pages/JoinPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignupPage.tsx
  src/store/auth/authApi.ts
  src/store/auth/authStore.ts
Labels: feat

#64 feat(#56): 마이페이지 연결, 조인페이지 로그아웃 버튼 변경, 회원탈퇴 기능 활성화
  .env
  src/App.tsx
  src/api/userApi.ts
  src/assets/icons/IconUser.tsx
  src/assets/icons/RocketIcon.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Header.tsx
  src/components/mypage/ActionBox.tsx
  src/components/mypage/MyPageBackground.tsx
  src/components/mypage/MyPageHeader.tsx
  src/components/mypage/PersonalInfoCard.tsx
  src/components/mypage/README.md
  src/components/mypage/ReportChart.tsx
  src/components/mypage/ReportsSection.tsx
  src/components/mypage/index.ts
  src/pages/MyPage.tsx
  src/store/authStore.ts
Labels: Feature

#67 chore(#66): 자잘한 라벨들 수정
  src/components/join/GuestActionContainer.tsx
  src/components/signup/SignupCard.tsx
  src/components/student-class/EditorPanel/EditorPanel.tsx
  src/components/student-class/Header.tsx
  src/components/teacher-class/EditorPanel/EditorPanel.tsx
  src/components/teacher-class/Header.tsx
  src/pages/StudentClassPage.tsx
  src/pages/TeacherClassPage.tsx
Labels: Chore

#95 feat(#94): 실시간 커서 보여주기 기능 개발
  src/components/student-class/EditorPanel/EditorPanel.tsx
  src/components/teacher-class/EditorPanel/EditorPanel.tsx
  src/index.css
  src/pages/StudentClassPage.tsx
  src/pages/TeacherClassPage.tsx
  src/store/studentStore.ts
  src/store/teacherStore.ts
Labels: Feature

#97 fix(#96): 학생에디터 말풍선 남는 문제 해결 및 중복 소켓리스너 삭제
  src/pages/StudentClassPage.tsx
  src/pages/TeacherClassPage.tsx
Labels: Bug

#104 feat(#103): 음성 채팅 기능 개발
  package-lock.json
  package.json
  src/components/common/VoiceChatModal.tsx
  src/components/common/logoutApi.ts
  src/components/student-class/Header.tsx
  src/components/teacher-class/Header.tsx
  src/hooks/useVoiceChat.ts
  src/pages/StudentClassPage.tsx
  src/pages/TeacherClassPage.tsx
  vite.config.ts
Labels: Feature

#100 feat(#74): 배포 파이프라인에 NginX 설정 파일 추가
  .github/workflows/deploy.yml
  .vscode/settings.json
  Dockerfile.prod
  ecs-task-definition.json
  nginx/coconut.conf.template
Labels: Bug, Chore

#165 feat(#164): 비밀번호 변경 구현 및 alert 수정
  package-lock.json
  src/api/userApi.ts
  src/components/mypage/AccountManagementView.tsx
  src/components/mypage/PasswordChangeModal.tsx
  src/components/signup/SignupCard.tsx
  src/components/student-class/Header.tsx
  src/components/teacher-class/Header.tsx
  src/pages/MyPage.tsx
  src/store/authStore.ts
Labels: Feature

#167 fix(#166): 타이머 새로고침 문제 해결
  src/components/student-class/EditorPanel/EditorPanel.tsx
  src/components/teacher-class/Header.tsx
  src/pages/TeacherClassPage.tsx
Labels: fix

#187 fix(#186):레이어 지우기 버튼 오류 해결
  src/components/common/SvgOverlay.tsx
  src/components/common/VoiceChatModal.tsx
Labels: fix

#192 fix(#191): 실시간 분석 패널 번쩍거림 해결
  src/analysis/complexityAnalyzer.ts
  src/components/analysis/StaticAnalysisReport.tsx
Labels: fix

#194 fix(#193): 학생 리포트 뷰 롤백
  src/components/report/StudentReportView.tsx
  src/pages/JoinPage.tsx
Labels: fix

#205 fix(#204): 커서 복구 및 diff 적용 - 에디터 ux 개선
  package-lock.json
  package.json
  src/components/student-class/EditorPanel/EditorPanel.tsx
  src/components/teacher-class/EditorPanel/EditorPanel.tsx
  src/components/teacher-class/ProblemPanel/ProblemDetailModal.tsx
  src/pages/StudentClassPage.tsx
  src/pages/TeacherClassPage.tsx
Labels: fix

#225 fix(#224): 같은 라인 동시편집 경고창 추가
  src/components/student-class/EditorPanel/EditorPanel.tsx
  src/components/teacher-class/EditorPanel/EditorPanel.tsx
Labels: Bug
